### ISSUE TITLE
Allow retrying at Scenario level

### ISSUE THREAD

**Issue by AdenFlorian** [webdriverio-boneyard/wdio-cucumber-framework#106]
I see that retries for individual steps are supported, and I think retrying of Scenarios would also be beneficial (particularly for a project that I'm working on).

# Proposal
New number config option called **numberOfTimesToRetryFailedScenario**.
When set to 0, it does what it currently does (fail the first time it fails).
When set to 1, and a Scenario fails on the first try, that Scenario will be rerun from the start, and if it fails on the second run, then let the Scenario fail.
Follow that pattern for 2 or more retries.

**Comment by christian-bromann** [comment]
I guess this can be a useful feature, feel free to propose a PR

**Comment by deepikadixitb** [comment]
I am really looking forward to this feature. please update once it is there.

**Comment by christian-bromann** [comment]
@deepikadixitb please provide a PR

**Comment by syedasadulhaq** [comment]
any update on this?

**Comment by abjerstedt** [comment]
@syedasadulhaq We have launched cucumber on webdriverio v5 months ago. We will not be doing feature enhancements on this repository.

**Comment by syedasadulhaq** [comment]
Thanks for the prompt response @abjerstedt. I'm using "webdriverio": "^5.11.13",
I believe the "retry flaky tests in scenario level" is not available in wdio 5 (https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-cucumber-framework) either. Please correct me if I'm wrong. Thanks!

**Comment by abjerstedt** [comment]
@syedasadulhaq Then you should look for updates in the webdriverio repository :). If there isn't already an issue for this there, feel free to add a new feature enhancement request.

**Comment by syedasadulhaq** [comment]
ok, thanks
